name: Fix lint probles
on: push

jobs: 
  run:
    name: Auto-fix with autopep8
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-node@v1
      with:
        python-version: 3.8
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install autopep8

    - name: Update source code
      run: |
        autopep8 --in-place --recursive --aggressive --aggressive .
        echo 'Finish'

    - name: Commit changes
      uses: EndBug/add-and-commit@v4
      with:
        author_name: mezgoodle
        author_email: mezgoodle@gmail.com
        message: "Update code via CI"
        add: "*.py"
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}